# Generated by Django 4.2.8 on 2023-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(
                choices=[
                    ('bmw', 'bmw'),
                    ('mercedes', 'mercedes'),
                    ('audi', 'audi'),
                    ('porsche', 'porsche'),
                    ('nissan', 'nissan'),
                    ('mitsubishi', 'mitsubishi'),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
