# Generated by Django 4.2.8 on 2023-12-08 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_post_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PexelsImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
